#!/usr/bin/env python3
"""Generate the CJK bitmap font header used by xdrv_95_aipassport_screen.ino.

The AI Passport boot screen shows a few fixed Chinese lines.  This script
rasterises exactly the characters used by those lines into 24x24 1-bit
bitmaps and writes them to

    tasmota/tasmota_xdrv_driver/aipassport_cjk_font.h

Font: Noto Sans SC (SIL Open Font License 1.1)
      https://fonts.google.com/noto/specimen/Noto+Sans+SC
Only the rasterised glyph data is embedded in the firmware, no font file is
redistributed with the repository.

Usage:
    python tools/gen_aipassport_cjk_font.py [--font <path>] [--out <path>]

Edit TEXT below (and the matching strings in the driver) when the wording
changes, then rerun the script.
"""

from __future__ import annotations

import argparse
import os
import pathlib
import sys

from PIL import Image, ImageDraw, ImageFont

GLYPH = 24
TEXT = [
    "无线网络设置",
    "第一步：连接热点",
    "第二步：打开网页",
    "已连接无线网",
    "网络名称：",
    "管理页面：",
]

FONT_CANDIDATES = [
    r"%LOCALAPPDATA%\Microsoft\Windows\Fonts\NotoSansSC-VF.ttf",
    r"C:\Windows\Fonts\NotoSansSC-VF.ttf",
    r"C:\Windows\Fonts\NotoSansSC-Regular.otf",
    "/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc",
    "/System/Library/Fonts/PingFang.ttc",
]

DEFAULT_OUT = pathlib.Path(__file__).resolve().parent.parent / "tasmota" / "tasmota_xdrv_driver" / "aipassport_cjk_font.h"


def find_font(explicit: str | None) -> pathlib.Path:
    if explicit:
        path = pathlib.Path(explicit)
        if not path.exists():
            sys.exit(f"font not found: {path}")
        return path
    for candidate in FONT_CANDIDATES:
        path = pathlib.Path(os.path.expandvars(candidate))
        if path.exists():
            return path
    sys.exit("no candidate font found, pass --font")


def rasterise(font_path: pathlib.Path) -> dict[str, bytes]:
    font = ImageFont.truetype(str(font_path), GLYPH)
    try:  # variable font: use a medium weight when available
        font.set_variation_by_axes([500])
    except Exception:
        pass

    glyphs: dict[str, bytes] = {}
    for char in sorted(set("".join(TEXT))):
        image = Image.new("L", (GLYPH, GLYPH), 0)
        ImageDraw.Draw(image).text((GLYPH // 2, GLYPH // 2), char, font=font, fill=255, anchor="mm")
        packed = bytearray()
        for y in range(GLYPH):
            row = 0
            for x in range(GLYPH):
                row = (row << 1) | (1 if image.getpixel((x, y)) >= 100 else 0)
            for byte_index in range(GLYPH // 8):
                packed.append((row >> (8 * (GLYPH // 8 - 1 - byte_index))) & 0xFF)
        glyphs[char] = bytes(packed)
    return glyphs


def write_header(glyphs: dict[str, bytes], font_path: pathlib.Path, out: pathlib.Path) -> None:
    chars = list(glyphs)
    lines = [
        "// Generated by tools/gen_aipassport_cjk_font.py - do not edit manually.",
        "//",
        f"// Font: Noto Sans SC (SIL Open Font License 1.1), {GLYPH}x{GLYPH} 1-bit glyphs.",
        "// Rerun the generator after changing the screen texts.",
        "",
        f"#define APS_CJK_GLYPH_W {GLYPH}",
        f"#define APS_CJK_GLYPH_H {GLYPH}",
        f"#define APS_CJK_GLYPH_BYTES {GLYPH * GLYPH // 8}",
        "",
        "static const uint16_t APS_CJK_CODEPOINTS[] = {",
        "  " + ", ".join(f"0x{ord(char):04X}" for char in chars) + ",",
        "};",
        "",
        "static const uint16_t APS_CJK_OFFSETS[] = {",
        "  " + ", ".join(str(i * GLYPH * GLYPH // 8) for i in range(len(chars))) + ",",
        "};",
        "",
        "static const uint8_t APS_CJK_BITS[] = {",
    ]
    for char in chars:
        blob = glyphs[char]
        lines.append(f"  // {char}")
        for offset in range(0, len(blob), 12):
            chunk = blob[offset:offset + 12]
            lines.append("  " + ", ".join(f"0x{value:02X}" for value in chunk) + ",")
    lines.append("};")
    lines.append("")

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"{len(chars)} glyphs ({len(chars) * GLYPH * GLYPH // 8} bytes) from {font_path}")
    print(f"written: {out}")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--font")
    parser.add_argument("--out", default=str(DEFAULT_OUT))
    args = parser.parse_args()

    font_path = find_font(args.font)
    glyphs = rasterise(font_path)
    write_header(glyphs, font_path, pathlib.Path(args.out))


if __name__ == "__main__":
    main()
